# Generated by Django 4.2.6 on 2023-11-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
