# Generated by Django 4.2.6 on 2023-11-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_reservationdb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='RepeatedPassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
