# Generated by Django 4.2.6 on 2023-12-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_checkoutdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutdb',
            old_name='EmailId',
            new_name='ProductName',
        ),
        migrations.RemoveField(
            model_name='checkoutdb',
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='checkoutdb',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='checkoutdb',
            name='TotalPrice',
        ),
        migrations.RemoveField(
            model_name='checkoutdb',
            name='UserName',
        ),
        migrations.AlterField(
            model_name='checkoutdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
