# Generated by Django 4.2.6 on 2023-12-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='Items',
            field=models.ManyToManyField(blank=True, related_name='checkout_items', to='Frontend.cartdb'),
        ),
    ]
