# Generated by Django 4.2.6 on 2023-11-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finalapp', '0002_productdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('EmailId', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.ImageField(blank=True, null=True, upload_to='')),
                ('Message', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
